# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wolong/routing/v1/routing_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from wolong.geo.v1 import geo_pb2 as wolong_dot_geo_dot_v1_dot_geo__pb2
from wolong.routing.v1 import routing_pb2 as wolong_dot_routing_dot_v1_dot_routing__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='wolong/routing/v1/routing_service.proto',
  package='wolong.routing.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\'wolong/routing/v1/routing_service.proto\x12\x11wolong.routing.v1\x1a\x17wolong/geo/v1/geo.proto\x1a\x1fwolong/routing/v1/routing.proto\"\xa4\x01\n\x0fGetRouteRequest\x12*\n\x04type\x18\x01 \x01(\x0e\x32\x1c.wolong.routing.v1.RouteType\x12&\n\x05start\x18\x02 \x01(\x0b\x32\x17.wolong.geo.v1.Position\x12$\n\x03\x65nd\x18\x03 \x01(\x0b\x32\x17.wolong.geo.v1.Position\x12\x17\n\x0f\x61\x63\x63\x65ss_revision\x18\x04 \x01(\x03\"@\n\x10GetRouteResponse\x12,\n\x08journeys\x18\x01 \x03(\x0b\x32\x1a.wolong.routing.v1.Journey2e\n\x0eRoutingService\x12S\n\x08GetRoute\x12\".wolong.routing.v1.GetRouteRequest\x1a#.wolong.routing.v1.GetRouteResponseb\x06proto3'
  ,
  dependencies=[wolong_dot_geo_dot_v1_dot_geo__pb2.DESCRIPTOR,wolong_dot_routing_dot_v1_dot_routing__pb2.DESCRIPTOR,])




_GETROUTEREQUEST = _descriptor.Descriptor(
  name='GetRouteRequest',
  full_name='wolong.routing.v1.GetRouteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='wolong.routing.v1.GetRouteRequest.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start', full_name='wolong.routing.v1.GetRouteRequest.start', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end', full_name='wolong.routing.v1.GetRouteRequest.end', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='access_revision', full_name='wolong.routing.v1.GetRouteRequest.access_revision', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=285,
)


_GETROUTERESPONSE = _descriptor.Descriptor(
  name='GetRouteResponse',
  full_name='wolong.routing.v1.GetRouteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='journeys', full_name='wolong.routing.v1.GetRouteResponse.journeys', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=351,
)

_GETROUTEREQUEST.fields_by_name['type'].enum_type = wolong_dot_routing_dot_v1_dot_routing__pb2._ROUTETYPE
_GETROUTEREQUEST.fields_by_name['start'].message_type = wolong_dot_geo_dot_v1_dot_geo__pb2._POSITION
_GETROUTEREQUEST.fields_by_name['end'].message_type = wolong_dot_geo_dot_v1_dot_geo__pb2._POSITION
_GETROUTERESPONSE.fields_by_name['journeys'].message_type = wolong_dot_routing_dot_v1_dot_routing__pb2._JOURNEY
DESCRIPTOR.message_types_by_name['GetRouteRequest'] = _GETROUTEREQUEST
DESCRIPTOR.message_types_by_name['GetRouteResponse'] = _GETROUTERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetRouteRequest = _reflection.GeneratedProtocolMessageType('GetRouteRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETROUTEREQUEST,
  '__module__' : 'wolong.routing.v1.routing_service_pb2'
  # @@protoc_insertion_point(class_scope:wolong.routing.v1.GetRouteRequest)
  })
_sym_db.RegisterMessage(GetRouteRequest)

GetRouteResponse = _reflection.GeneratedProtocolMessageType('GetRouteResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETROUTERESPONSE,
  '__module__' : 'wolong.routing.v1.routing_service_pb2'
  # @@protoc_insertion_point(class_scope:wolong.routing.v1.GetRouteResponse)
  })
_sym_db.RegisterMessage(GetRouteResponse)



_ROUTINGSERVICE = _descriptor.ServiceDescriptor(
  name='RoutingService',
  full_name='wolong.routing.v1.RoutingService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=353,
  serialized_end=454,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetRoute',
    full_name='wolong.routing.v1.RoutingService.GetRoute',
    index=0,
    containing_service=None,
    input_type=_GETROUTEREQUEST,
    output_type=_GETROUTERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ROUTINGSERVICE)

DESCRIPTOR.services_by_name['RoutingService'] = _ROUTINGSERVICE

# @@protoc_insertion_point(module_scope)
