# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wolong/geo/v1/geo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wolong/geo/v1/geo.proto',
  package='wolong.geo.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17wolong/geo/v1/geo.proto\x12\rwolong.geo.v1\"6\n\x0fLongLatPosition\x12\x11\n\tlongitude\x18\x01 \x01(\x01\x12\x10\n\x08latitude\x18\x02 \x01(\x01\"\"\n\nXYPosition\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\"*\n\x0cLanePosition\x12\x0f\n\x07lane_id\x18\x01 \x01(\r\x12\t\n\x01s\x18\x02 \x01(\x02\"\x1d\n\x0bPoiPosition\x12\x0e\n\x06poi_id\x18\x01 \x01(\r\"\x9d\x02\n\x08Position\x12\x34\n\rlane_position\x18\x01 \x01(\x0b\x32\x1b.wolong.geo.v1.LanePositionH\x00\x12\x32\n\x0cpoi_position\x18\x02 \x01(\x0b\x32\x1a.wolong.geo.v1.PoiPositionH\x00\x12=\n\x10longlat_position\x18\x03 \x01(\x0b\x32\x1e.wolong.geo.v1.LongLatPositionH\x01\x88\x01\x01\x12\x33\n\x0bxy_position\x18\x04 \x01(\x0b\x32\x19.wolong.geo.v1.XYPositionH\x02\x88\x01\x01\x42\x0e\n\x0cmap_positionB\x13\n\x11_longlat_positionB\x0e\n\x0c_xy_position\"i\n\x0fLongLatRectArea\x12*\n\x02ne\x18\x01 \x01(\x0b\x32\x1e.wolong.geo.v1.LongLatPosition\x12*\n\x02sw\x18\x02 \x01(\x0b\x32\x1e.wolong.geo.v1.LongLatPositionb\x06proto3'
)




_LONGLATPOSITION = _descriptor.Descriptor(
  name='LongLatPosition',
  full_name='wolong.geo.v1.LongLatPosition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='longitude', full_name='wolong.geo.v1.LongLatPosition.longitude', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='wolong.geo.v1.LongLatPosition.latitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=96,
)


_XYPOSITION = _descriptor.Descriptor(
  name='XYPosition',
  full_name='wolong.geo.v1.XYPosition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='wolong.geo.v1.XYPosition.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='wolong.geo.v1.XYPosition.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=132,
)


_LANEPOSITION = _descriptor.Descriptor(
  name='LanePosition',
  full_name='wolong.geo.v1.LanePosition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='lane_id', full_name='wolong.geo.v1.LanePosition.lane_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='s', full_name='wolong.geo.v1.LanePosition.s', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=176,
)


_POIPOSITION = _descriptor.Descriptor(
  name='PoiPosition',
  full_name='wolong.geo.v1.PoiPosition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='poi_id', full_name='wolong.geo.v1.PoiPosition.poi_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=207,
)


_POSITION = _descriptor.Descriptor(
  name='Position',
  full_name='wolong.geo.v1.Position',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='lane_position', full_name='wolong.geo.v1.Position.lane_position', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='poi_position', full_name='wolong.geo.v1.Position.poi_position', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='longlat_position', full_name='wolong.geo.v1.Position.longlat_position', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='xy_position', full_name='wolong.geo.v1.Position.xy_position', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='map_position', full_name='wolong.geo.v1.Position.map_position',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_longlat_position', full_name='wolong.geo.v1.Position._longlat_position',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_xy_position', full_name='wolong.geo.v1.Position._xy_position',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=210,
  serialized_end=495,
)


_LONGLATRECTAREA = _descriptor.Descriptor(
  name='LongLatRectArea',
  full_name='wolong.geo.v1.LongLatRectArea',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ne', full_name='wolong.geo.v1.LongLatRectArea.ne', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sw', full_name='wolong.geo.v1.LongLatRectArea.sw', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=497,
  serialized_end=602,
)

_POSITION.fields_by_name['lane_position'].message_type = _LANEPOSITION
_POSITION.fields_by_name['poi_position'].message_type = _POIPOSITION
_POSITION.fields_by_name['longlat_position'].message_type = _LONGLATPOSITION
_POSITION.fields_by_name['xy_position'].message_type = _XYPOSITION
_POSITION.oneofs_by_name['map_position'].fields.append(
  _POSITION.fields_by_name['lane_position'])
_POSITION.fields_by_name['lane_position'].containing_oneof = _POSITION.oneofs_by_name['map_position']
_POSITION.oneofs_by_name['map_position'].fields.append(
  _POSITION.fields_by_name['poi_position'])
_POSITION.fields_by_name['poi_position'].containing_oneof = _POSITION.oneofs_by_name['map_position']
_POSITION.oneofs_by_name['_longlat_position'].fields.append(
  _POSITION.fields_by_name['longlat_position'])
_POSITION.fields_by_name['longlat_position'].containing_oneof = _POSITION.oneofs_by_name['_longlat_position']
_POSITION.oneofs_by_name['_xy_position'].fields.append(
  _POSITION.fields_by_name['xy_position'])
_POSITION.fields_by_name['xy_position'].containing_oneof = _POSITION.oneofs_by_name['_xy_position']
_LONGLATRECTAREA.fields_by_name['ne'].message_type = _LONGLATPOSITION
_LONGLATRECTAREA.fields_by_name['sw'].message_type = _LONGLATPOSITION
DESCRIPTOR.message_types_by_name['LongLatPosition'] = _LONGLATPOSITION
DESCRIPTOR.message_types_by_name['XYPosition'] = _XYPOSITION
DESCRIPTOR.message_types_by_name['LanePosition'] = _LANEPOSITION
DESCRIPTOR.message_types_by_name['PoiPosition'] = _POIPOSITION
DESCRIPTOR.message_types_by_name['Position'] = _POSITION
DESCRIPTOR.message_types_by_name['LongLatRectArea'] = _LONGLATRECTAREA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LongLatPosition = _reflection.GeneratedProtocolMessageType('LongLatPosition', (_message.Message,), {
  'DESCRIPTOR' : _LONGLATPOSITION,
  '__module__' : 'wolong.geo.v1.geo_pb2'
  # @@protoc_insertion_point(class_scope:wolong.geo.v1.LongLatPosition)
  })
_sym_db.RegisterMessage(LongLatPosition)

XYPosition = _reflection.GeneratedProtocolMessageType('XYPosition', (_message.Message,), {
  'DESCRIPTOR' : _XYPOSITION,
  '__module__' : 'wolong.geo.v1.geo_pb2'
  # @@protoc_insertion_point(class_scope:wolong.geo.v1.XYPosition)
  })
_sym_db.RegisterMessage(XYPosition)

LanePosition = _reflection.GeneratedProtocolMessageType('LanePosition', (_message.Message,), {
  'DESCRIPTOR' : _LANEPOSITION,
  '__module__' : 'wolong.geo.v1.geo_pb2'
  # @@protoc_insertion_point(class_scope:wolong.geo.v1.LanePosition)
  })
_sym_db.RegisterMessage(LanePosition)

PoiPosition = _reflection.GeneratedProtocolMessageType('PoiPosition', (_message.Message,), {
  'DESCRIPTOR' : _POIPOSITION,
  '__module__' : 'wolong.geo.v1.geo_pb2'
  # @@protoc_insertion_point(class_scope:wolong.geo.v1.PoiPosition)
  })
_sym_db.RegisterMessage(PoiPosition)

Position = _reflection.GeneratedProtocolMessageType('Position', (_message.Message,), {
  'DESCRIPTOR' : _POSITION,
  '__module__' : 'wolong.geo.v1.geo_pb2'
  # @@protoc_insertion_point(class_scope:wolong.geo.v1.Position)
  })
_sym_db.RegisterMessage(Position)

LongLatRectArea = _reflection.GeneratedProtocolMessageType('LongLatRectArea', (_message.Message,), {
  'DESCRIPTOR' : _LONGLATRECTAREA,
  '__module__' : 'wolong.geo.v1.geo_pb2'
  # @@protoc_insertion_point(class_scope:wolong.geo.v1.LongLatRectArea)
  })
_sym_db.RegisterMessage(LongLatRectArea)


# @@protoc_insertion_point(module_scope)
